# Site
site_name: PPDS Documentation
site_description: Documentation for PaoPao's DataStore Modules
site_author: PaoPaoDev (Paopun20)
site_url: https://Paopun20.github.io/PaoPaoDataStore/

# repo
repo_url: https://github.com/Paopun20/PaoPaoDataStore
repo_name: PaoPao's DataStore module

# theme or config
theme:
  name: material
  language: en
  features:
    - navigation.expand
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight

nav:
  - Home: index.md
  - API Reference: api.md

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - def_list
  - attr_list
