[package]
name = "paopun20/paopaodatastore"
authors = [
    "Paopun20"
]
description = "PaoPao's DataStore - A fast, server-side Roblox DataStore wrapper with caching, cross-server invalidation, migrations, and lifecycle hooks."
version = "1.1.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
repository = "https://github.com/Paopun20/PaoPaoDataStore"
bugs = "https://github.com/Paopun20/PaoPaoDataStore/issues"
homepage = "https://github.com/Paopun20/PaoPaoDataStore"
exclude = [".github/*", "docs/*", "extra/*", "**/*.md", "**/*.yml", "**/*.txt"]
include = ["src/*"]