on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build

    steps:
      - name: Checkout files
        uses: actions/checkout@v3

      - name: Build
        uses: CompeyDev/rojo-build-action@0.1.5
        with:
          output: PaoPaoDataStore.rbxm
          type: rbxm

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PaoPaoDataStore
          path: PaoPaoDataStore.rbxm

      - name: Commit and push if there are changes
        run: |-
          git diff
          git config --global user.email "hi@devcomp.xyz"
          git config --global user.name "BuildBot"
          git diff --quiet || (git add -u && git commit -m "chore(deploy): build rojo project")
          git push               